CREATE TABLE IF NOT EXISTS Users (
    UserID INT PRIMARY KEY,
    FirstName VARCHAR(40) NOT NULL,
    Surname VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(100),
    PhoneNum VARCHAR(15) UNIQUE NOT NULL
);